Miscellaneous
biojava/biojava pull request #1002
Opened 2021-11-27 23:03 UTC by aalhossary

2021-12-02 00:42 UTC, josemduarte requested changes
Thanks!

2021-12-02 00:42 UTC, josemduarte commented on biojava-structure/src/main/java/org/biojava/nbio/structure/HetatomImpl.java
> +				logger.warn("An atom with name " + atom.getName() + " " + altLocStr + " is already present in group: " + this.toString() + ". The atom with serial " + existingAtom.getPDBserial() + " will be igno
Good catch, thanks!

2021-12-02 00:42 UTC, josemduarte commented on biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/FastaGeneWriterTest.java
> +        String [] lines =  output.split("\r?\n");
How about using `\R`?, see https://www.baeldung.com/java-string-split-by-newline

2021-12-02 17:15 UTC, josemduarte approved these changes
Thanks! LGTM

2021-12-02 20:28 UTC, aalhossary commented
Thank you for the tip. I didn't know about \R before.

Do you have any idea why it failed twice?

2021-12-02 21:47 UTC, josemduarte commented
It looks like there are problems with the SCOP servers. I'll try it again tomorrow.

2021-12-06 03:58 UTC, aalhossary commented
I triggered a new build which was successful this time. Will merge now.

2021-12-06 03:59 UTC, merged