Additional tests of null PDBIds
biojava/biojava pull request #1021
Opened 2022-02-02 09:20 UTC by sbliven

This addresses #1019 and was developed in parallel with @josemduarte's fix #1020. It has been rebased to remove duplicated effort, and now consists mostly of additional tests for the bug.

2022-02-02 10:41 UTC, aalhossary approved these changes
Thanks! LGTM

2022-02-02 10:41 UTC, aalhossary approved these changes
Thanks! LGTM

2022-02-02 17:56 UTC, josemduarte requested changes
Thank you. Very needed tests!

2022-02-02 17:56 UTC, josemduarte commented on biojava-structure/src/main/java/org/biojava/nbio/structure/io/PDBFileParser.java
> +			if(pdbCode.isBlank()) {
It seems that `String.isBlank()` is a java 11 feature that we can't use just yet. At least that's what IntelliJ tells me. Interestingly the tests passed in CI, not sure why.

In any case, I'd like to move to java 11 soon. I think it is long overdue. We'll try to address that separately.

2022-02-02 17:56 UTC, josemduarte commented on biojava-structure/src/main/java/org/biojava/nbio/structure/io/cif/CifStructureConsumerImpl.java
> +            if(pdbCode.isBlank()){
Same comment

2022-02-02 17:56 UTC, josemduarte commented on biojava-structure/src/test/resources/AF-A0A0R4IYF1-F1-model_v2.pdb
> +HEADER                                            01-JUL-21
Could you make this file smaller? Simply keep 2-3 residues from ATOM and SEQRES

2023-01-30 22:03 UTC, josemduarte approved these changes
I'll approve, `isBlank()` will be ok once #1053 is merged

2023-01-30 22:52 UTC, josemduarte commented
I'll supersede this PR by a new one so that I can truncate the large PDB file before merging

2023-01-30 22:52 UTC, closed without merging