[WIP] Github issue 843
biojava/biojava pull request #919
Opened 2021-03-01 18:13 UTC by MaxGreil

#### Reference Issue
Partly fixes issue #843 

#### What does this implement/fix? Explain your changes.
- Corrected GenbankReader.java to parse anticodon qualifiers when they line wrap.
- Wrote new testGithub843 in GenbankReaderTest.java
- Added mentioned file NC_018080.gb downloaded from https://www.ncbi.nlm.nih.gov/nuccore/NC_018080

#### Additional comments
@josemduarte , can you please tell me where I can get NC_018080 in .embl file format? I couldn't find it.

2021-03-02 00:17 UTC, josemduarte requested changes
Thanks @MaxGreil ! this is great progress.

Adding the full 14MB genbank file is a bit too much for a unit test. We should avoid adding a lot of data if not needed. The ideal unit test is a test that goes through a few lines only and asserts that the behaviour is as expected. For instance you can get the few lines excerpt from the genbank record to demonstrate the issue. You can even keep the few lines as a string constant inside the test.

2021-03-02 17:40 UTC, MaxGreil commented
Hi @josemduarte , I reduced the size of file NC_018080.gb to contain only one relevant case with qualifier anticodon.

2021-03-02 17:49 UTC, heuermh commented
Is the fix for `transl_except` as simple?  Though here aren't any examples of these kind of failing lines in the linked issue

2021-03-03 00:19 UTC, aalhossary commented
ور

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Michael L Heuer <notifications@github.com>
Sent: Wednesday, March 3, 2021 1:49:32 AM
To: biojava/biojava <biojava@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [biojava/biojava] [WIP] Github issue 843 (#919)


Is the fix for transl_except as simple? Though here aren't any examples of these kind of failing lines in the linked issue

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/biojava/biojava/pull/919#issuecomment-789091156>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA35TI2BI3RGNUQMYOGUNJDTBUQKZANCNFSM4YNA2ZVA>.

2021-03-03 11:52 UTC, MaxGreil commented
I added a fix for qualifier `transl_except` in the genebank parser according to the documentation.

@heuermh thank you for posting the documentation for qualifier `transl_except`. Do you know an example file for qualifier `transl_except` with line wrap? Or is testGithub843 sufficient as it is?

@josemduarte does it make sense to split this PR for issue #843 into 2 separate PRs, i.e. one PR for the genebank parser and one PR for the embl parser?

2021-03-05 05:52 UTC, josemduarte commented on biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/GenbankReaderTest.java
> +			assertFalse(anticodon.contains(" "));
How about also asserting that the string is exactly as expected? If I understand it right, it should be: `(pos:complement(1123552..1123554),aa:Leu,seq:caa)`

2021-03-05 23:51 UTC, josemduarte commented
> Do you know an example file for qualifier transl_except with line wrap? Or is testGithub843 sufficient as it is?

I would simply fabricate an example for transl_except with wrapping in the same gb file excerpt text you have added.

>  does it make sense to split this PR for issue #843 into 2 separate PRs, i.e. one PR for the genebank parser and one PR for the embl parser?

Do we already have an EMBL file parser somewhere in BioJava? Sorry I don't know well this part of BioJava. If we do and it's only about fixing it, then please go ahead and make it part of this PR. It will only need an additional unit test (again, it's ok to have fabricated data).

2021-03-06 13:42 UTC, MaxGreil commented
I added a line in file `NC_018080.gb` qualifier `transl_except` and tested for correct parsing.

However, I have an additional question:

I had a look at the EMBL file parser with test `givenAnEmilFileWhenProcessEmilFileThanTheSequenceShouldReturnAsExpected` in `biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/embl/EmblReaderTest.java`. 
To my understanding, the FeatureTable in file `embl.test`  is not parsed at all. 
Please have a look at `biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/embl/EmblRecord.java`. Variable `featureTable` is just a String that gets assign and overwritten by the last value.

@josemduarte , should I open a new issue for this problem?

2021-03-09 17:07 UTC, josemduarte commented
> I added a line in file NC_018080.gb qualifier transl_except and tested for correct parsing.

Great, thanks @MaxGreil ! I think this looks good now. @heuermh could you double check it too?

> I had a look at the EMBL file parser with test givenAnEmilFileWhenProcessEmilFileThanTheSequenceShouldReturnAsExpected in biojava-core/src/test/java/org/biojava/nbio/core/sequence/io/embl/EmblReaderTest.java.
To my understanding, the FeatureTable in file embl.test is not parsed at all.
Please have a look at biojava-core/src/main/java/org/biojava/nbio/core/sequence/io/embl/EmblRecord.java. Variable featureTable is just a String that gets assign and overwritten by the last value.

Thanks for investigating. Indeed that deserves another issue separate from #843

2021-03-24 23:37 UTC, josemduarte commented
I'll merge this by the end of the week if there's no other comments

2021-03-26 22:58 UTC, merged