Remove mains #966
biojava/biojava pull request #997
Opened 2021-11-16 08:57 UTC by richarda23

converting main methods to junit tests or removing altogether from biojava-core
each commit covers one removsl

2021-11-16 17:58 UTC, heuermh requested changes
Thanks!  Love to see a pull request that deletes 2x more lines than it adds.

2021-11-16 17:58 UTC, heuermh commented on biojava-core/src/main/java/org/biojava/nbio/core/sequence/GeneSequence.java
> +		// TODO should be IllegalArgumentException, is more specific
I agree, go ahead and make this change

2021-11-16 17:58 UTC, heuermh commented on biojava-core/src/main/java/demo/UncompressFile.java
> +package demo;
This new file (and others in this pull request) need the license header.  For example
https://github.com/biojava/biojava/blob/master/biojava-aa-prop/src/main/java/demo/BioJavaAADemo.java#L1

2021-11-16 18:22 UTC, heuermh approved these changes

2021-11-16 18:48 UTC, richarda23 commented
changing the method signature of public ExonSequence addExon(AccessionID accession, int begin, int end) will be a breaking API change as it no longer declares a checked exception

2021-11-16 19:55 UTC, heuermh commented
Ah well, no reason to break compatibility here -- we could keep the method signature as `throws Exception` and just change the thrown exception to `IllegalArgumentException`, which extends `Exception` via `RuntimeException`.

2021-11-16 22:08 UTC, richarda23 commented
hm, it's a bit non-standard to declare runtime exceptions in method signatures, they are normally documented in javadoc: https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html. Just thinking about it some more, calling code will already be handling the checked exception , so won't need to change.  I think only subclasses overriding this method may have to change their signature, which will be a much smaller set of cases.

2021-11-18 05:51 UTC, josemduarte approved these changes
Looks great to me, thanks @richarda23 

Regarding the change of signature in `GeneSequence.addExon`, I think we can allow it even though 6.0.0 is out already, because a) it is a very minor, b) the 6.0.0 release was sort of invalid because it breaks java-8 run time compatibility, see #996 . We need a 6.0.1 soon to fix that

2021-11-18 05:51 UTC, josemduarte commented on biojava-core/src/main/java/org/biojava/nbio/core/sequence/GeneSequence.java
> +			throw new IllegalArgumentException("Duplicate accesion id " + accession.getID());
Thanks for this change. This is a lot cleaner now. I think generally `throws Exception` signatures should be avoided

2021-11-19 04:42 UTC, merged

2021-11-19 04:43 UTC, heuermh commented
Thank you, @richarda23 @josemduarte